# Generated by Django 4.0.5 on 2022-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('primary_image', models.CharField(default='', max_length=50)),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('status', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField()),
                ('order', models.IntegerField()),
                ('created_by', models.CharField(default='', max_length=50)),
                ('updated_by', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
