# Generated by Django 4.0.5 on 2022-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0003_alter_blog_created_at_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
