# Generated by Django 4.0.5 on 2022-08-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0005_alter_blog_created_at_alter_blog_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_type',
        ),
    ]
