# Generated by Django 4.0.5 on 2022-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0006_remove_blog_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='active',
            field=models.BooleanField(),
        ),
    ]
