# Generated by Django 4.0.5 on 2022-08-16 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0012_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=50)),
                ('likes', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('status', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('created_by', models.CharField(default='', max_length=50)),
                ('updated_by', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_id', to='task1_app.blog')),
            ],
        ),
    ]
