# Generated by Django 4.0.5 on 2022-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0013_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
