# Generated by Django 4.0.5 on 2022-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0014_alter_comments_dislike_alter_comments_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
