# Generated by Django 4.0.5 on 2022-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0015_alter_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
