# Generated by Django 4.0.5 on 2022-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0016_alter_comments_dislike_alter_comments_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
