# Generated by Django 4.0.5 on 2022-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0018_alter_comments_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
