# Generated by Django 4.0.5 on 2022-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0020_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
