# Generated by Django 4.0.5 on 2022-09-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0021_alter_register_email_alter_register_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
