# Generated by Django 4.0.5 on 2022-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_app', '0033_alter_user_email_alter_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
